In [5]:
import os

print("현재 위치:", os.getcwd())

print("\n현재 폴더의 파일:")
print(os.listdir("."))

print("\n../raw_data 폴더:")
if os.path.exists("../raw_data"):
    print(os.listdir("../raw_data"))
else:
    print("없음")

print("\nraw_data 폴더:")
if os.path.exists("raw_data"):
    print(os.listdir("raw_data"))
else:
    print("없음")

현재 위치: /Users/imsnmn/Documents/BSE_Climate_Policy/notebooks

현재 폴더의 파일:
['.DS_Store', '01_cpu_check.ipynb', '02_carbon_pricing_check.ipynb']

../raw_data 폴더:
['cpu_raw.csv', 'carbon_pricing_raw_2605.xlsx']

raw_data 폴더:
없음

In [10]:
import pandas as pd

excel_file = "/Users/imsnmn/Documents/BSE_Climate_Policy/raw_data/carbon_pricing_raw_2605.xlsx"
carbon_gen = pd.read_excel(
    excel_file,
    sheet_name="Compliance_Gen Info",
    header=4
)

print(carbon_gen.shape)
print(carbon_gen.columns.tolist())

(139, 44)
['Unique ID', 'Instrument name', 'Type', 'Status', 'Jurisdiction covered', 'Share of jurisdiction emissions covered', 'Price on 1 April', 2021, 2022, 2023, 2024, 2025, 2026, 'Change', 'Government revenue', 2020, '2021.1', '2022.1', '2023.1', '2024.1', '2025.1', 'Change.1', 'Gases covered', 'Electricity and heat', 'Industry', 'Mining and extractives', 'Transport', 'Aviation', 'Buildings', 'Agriculture, forestry and fishing fuel use', 'Agricultural emissions', 'Waste', 'LULUCF', 'Fuels covered', 'Allocation approaches', 'Price or market management', 'Point of Regulation', 'Offset eligibility', 'Description', 'Recent developments', 'Coverage', 'Pricing and allocation', 'Compliance', 'Relation to other instruments']

In [11]:
carbon_gen.head()

,Unique ID,Instrument name,Type,Status,Jurisdiction covered,Share of jurisdiction emissions covered,Price on 1 April,2021,2022,2023,...,Allocation approaches,Price or market management,Point of Regulation,Offset eligibility,Description,Recent developments,Coverage,Pricing and allocation,Compliance,Relation to other instruments
0,Tax_AL,Albania carbon tax,Carbon tax,Implemented,Albania,"73% of jurisdiction emissions, 0.0098% of glob...","US$17 (ALL1,400)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,,Albania has postponed the entry into force of ...,,NaN,NaN,
1,ETS_AL,Albania ETS,ETS,Under consideration,Albania,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tax_CA_Alberta,Alberta carbon tax,Carbon tax,Abolished,Alberta,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ETS_CA_Alberta,Alberta TIER,ETS,Implemented,Alberta,"63% of jurisdiction emissions, 0.3007% of glob...",US$68 (CAN$95),31.834461,39.961637,48.03074,...,"Free allocation (Intensity-based), Set price",Set price trajectory,Point Source,"Yes, with quantitative limit",The Technology Innovation and Emissions Reduct...,"In May 2025, Alberta's government announced T...",Alberta’s TIER Regulation applies to all green...,Baselines (Intensity-based),Annual,Facilities covered by the TIER Regulation are ...
4,Tax_AN,Andorra carbon tax,Carbon tax,Implemented,Andorra,"95% of jurisdiction emissions, 0.0008% of glob...",US$35 (€30),NaN,33.156000,32.62500,...,NA,,NaN,NaN,NaN,Under the Energy Transition and Climate Change...,"The tax targets energy use across sectors, inc...",NA,NaN,Andorra’s carbon pricing is not linked to oth...

In [12]:
for i, col in enumerate(carbon_gen.columns):
    print(i, repr(col))

0 'Unique ID'
1 'Instrument name'
2 'Type'
3 'Status'
4 'Jurisdiction covered'
5 'Share of jurisdiction emissions covered'
6 'Price on 1 April'
7 2021
8 2022
9 2023
10 2024
11 2025
12 2026
13 'Change'
14 'Government revenue'
15 2020
16 '2021.1'
17 '2022.1'
18 '2023.1'
19 '2024.1'
20 '2025.1'
21 'Change.1'
22 'Gases covered'
23 'Electricity and heat'
24 'Industry'
25 'Mining and extractives'
26 'Transport'
27 'Aviation'
28 'Buildings'
29 'Agriculture, forestry and fishing fuel use'
30 'Agricultural emissions'
31 'Waste'
32 'LULUCF'
33 'Fuels covered'
34 'Allocation approaches'
35 'Price or market management'
36 'Point of Regulation'
37 'Offset eligibility'
38 'Description'
39 'Recent developments'
40 'Coverage'
41 'Pricing and allocation'
42 'Compliance'
43 'Relation to other instruments'

In [13]:
# 생략됐던 열 이름 확인
for i, col in enumerate(carbon_gen.columns):
    if 25 <= i <= 39:
        print(i, repr(col))

# 국가·제도·상태와 시행연도 관련 열만 찾아보기
carbon_gen[
    ["Unique ID", "Instrument name", "Type", "Status", "Jurisdiction covered"]
].head(10)

25 'Mining and extractives'
26 'Transport'
27 'Aviation'
28 'Buildings'
29 'Agriculture, forestry and fishing fuel use'
30 'Agricultural emissions'
31 'Waste'
32 'LULUCF'
33 'Fuels covered'
34 'Allocation approaches'
35 'Price or market management'
36 'Point of Regulation'
37 'Offset eligibility'
38 'Description'
39 'Recent developments'

,Unique ID,Instrument name,Type,Status,Jurisdiction covered
0,Tax_AL,Albania carbon tax,Carbon tax,Implemented,Albania
1,ETS_AL,Albania ETS,ETS,Under consideration,Albania
2,Tax_CA_Alberta,Alberta carbon tax,Carbon tax,Abolished,Alberta
3,ETS_CA_Alberta,Alberta TIER,ETS,Implemented,Alberta
4,Tax_AN,Andorra carbon tax,Carbon tax,Implemented,Andorra
5,Tax_AR,Argentina carbon tax,Carbon tax,Implemented,Argentina
6,ETS_AR,Argentina ETS,ETS,Under consideration,Argentina
7,ETS_AU1,Australia CPM,ETS,Abolished,Australia
8,ETS_AU2,Australia Safeguard Mechanism,ETS,Implemented,Australia
9,ETS_AT,Austria ETS,ETS,Implemented,Austria

In [14]:
countries = [
    "Australia", "Canada", "France", "Germany", "Ireland",
    "Italy", "Mexico", "New Zealand", "Spain",
    "United Kingdom", "United States", "European Union"
]

relevant = carbon_gen[
    carbon_gen["Jurisdiction covered"].astype(str).isin(countries)
].copy()

relevant[
    ["Unique ID", "Instrument name", "Type", "Status", "Jurisdiction covered"]
].to_string(index=False)

'Unique ID               Instrument name       Type              Status Jurisdiction covered\n  ETS_AU1                 Australia CPM        ETS           Abolished            Australia\n  ETS_AU2 Australia Safeguard Mechanism        ETS         Implemented            Australia\n  ETS_CA2                    Canada ETS        ETS   Under development               Canada\n   Tax_CA    Canada federal fuel charge Carbon tax           Abolished               Canada\n   ETS_CA           Canada federal OBPS        ETS         Implemented               Canada\n   Tax_FR             France carbon tax Carbon tax         Implemented               France\n   ETS_DE                   Germany ETS        ETS         Implemented              Germany\n   Tax_IE            Ireland carbon tax Carbon tax         Implemented              Ireland\n   Tax_MX             Mexico carbon tax Carbon tax         Implemented               Mexico\n   ETS_MX                    Mexico ETS        ETS         Implemented               Mexico\n   Tax_NZ        New Zealand carbon tax Carbon tax Under consideration          New Zealand\n   ETS_NZ               New Zealand ETS        ETS         Implemented          New Zealand\n   Tax_ES              Spain carbon tax Carbon tax         Implemented                Spain\n   Tax_UK       UK Carbon Price Support Carbon tax         Implemented       United Kingdom\n   ETS_UK                        UK ETS        ETS         Implemented       United Kingdom'

In [15]:
extra = carbon_gen[
    carbon_gen["Instrument name"].astype(str).str.contains(
        r"EU ETS|California|RGGI",
        case=False,
        regex=True
    )
]

extra[
    ["Unique ID", "Instrument name", "Type", "Status", "Jurisdiction covered"]
].to_string(index=False)

'        Unique ID            Instrument name       Type            Status Jurisdiction covered\n        Tax_MX_BC Baja California carbon tax Carbon tax         Abolished      Baja California\nETS_US_California             California CaT        ETS       Implemented           California\n           ETS_EU                     EU ETS        ETS       Implemented                EU27+\n          ETS_EU2                    EU ETS2        ETS Under development                EU27+\n        ETS_EU_IS                     EU ETS        ETS       Implemented              Iceland\n        ETS_EU_LI                     EU ETS        ETS       Implemented        Liechtenstein\n        ETS_EU_NO                     EU ETS        ETS       Implemented               Norway\n         ETS_RGGI                       RGGI        ETS       Implemented                 RGGI'

In [16]:
national = carbon_gen[
    carbon_gen["Jurisdiction covered"].astype(str).isin([
        "Australia", "Canada", "France", "Germany", "Ireland",
        "Italy", "Mexico", "New Zealand", "Spain",
        "United Kingdom", "United States"
    ])
]

eu_ets = carbon_gen[
    carbon_gen["Unique ID"].eq("ETS_EU")
]

inventory = pd.concat([national, eu_ets], ignore_index=True)

inventory = inventory[
    ["Unique ID", "Instrument name", "Type", "Status", "Jurisdiction covered"]
].drop_duplicates()

print(inventory.to_string(index=False))

Unique ID               Instrument name       Type              Status Jurisdiction covered
  ETS_AU1                 Australia CPM        ETS           Abolished            Australia
  ETS_AU2 Australia Safeguard Mechanism        ETS         Implemented            Australia
  ETS_CA2                    Canada ETS        ETS   Under development               Canada
   Tax_CA    Canada federal fuel charge Carbon tax           Abolished               Canada
   ETS_CA           Canada federal OBPS        ETS         Implemented               Canada
   Tax_FR             France carbon tax Carbon tax         Implemented               France
   ETS_DE                   Germany ETS        ETS         Implemented              Germany
   Tax_IE            Ireland carbon tax Carbon tax         Implemented              Ireland
   Tax_MX             Mexico carbon tax Carbon tax         Implemented               Mexico
   ETS_MX                    Mexico ETS        ETS         Implemented               Mexico
   Tax_NZ        New Zealand carbon tax Carbon tax Under consideration          New Zealand
   ETS_NZ               New Zealand ETS        ETS         Implemented          New Zealand
   Tax_ES              Spain carbon tax Carbon tax         Implemented                Spain
   Tax_UK       UK Carbon Price Support Carbon tax         Implemented       United Kingdom
   ETS_UK                        UK ETS        ETS         Implemented       United Kingdom
   ETS_EU                        EU ETS        ETS         Implemented                EU27+

In [17]:
import pandas as pd

policy_dates = pd.DataFrame([
    {"instrument_id": "ETS_EU",  "start_year": 2005, "end_year": None},
    {"instrument_id": "ETS_NZ",  "start_year": 2008, "end_year": None},
    {"instrument_id": "Tax_IE",  "start_year": 2010, "end_year": None},
    {"instrument_id": "ETS_AU1", "start_year": 2012, "end_year": 2014},
    {"instrument_id": "Tax_UK",  "start_year": 2013, "end_year": None},
    {"instrument_id": "Tax_FR",  "start_year": 2014, "end_year": None},
    {"instrument_id": "Tax_MX",  "start_year": 2014, "end_year": None},
    {"instrument_id": "Tax_CA",  "start_year": 2019, "end_year": 2025},
    {"instrument_id": "ETS_CA",  "start_year": 2019, "end_year": None},
])

policy_dates

  instrument_id  start_year  end_year
0        ETS_EU        2005       NaN
1        ETS_NZ        2008       NaN
2        Tax_IE        2010       NaN
3       ETS_AU1        2012    2014.0
4        Tax_UK        2013       NaN
5        Tax_FR        2014       NaN
6        Tax_MX        2014       NaN
7        Tax_CA        2019    2025.0
8        ETS_CA        2019       NaN

In [18]:
from pathlib import Path

project = Path.home() / "Documents" / "BSE_Climate_Policy"

policy_dates.to_csv(
    project / "processed_data" / "carbon_policy_dates_draft.csv",
    index=False
)

In [19]:
from pathlib import Path
import pandas as pd

project = Path.home() / "Documents" / "BSE_Climate_Policy"

countries = [
    "AUS", "CAN", "DEU", "ESP", "FRA", "GBR",
    "IRL", "ITA", "MEX", "NZL", "USA"
]

# 11개국 × 2000–2019년
carbon_panel = pd.MultiIndex.from_product(
    [countries, range(2000, 2020)],
    names=["country_code", "year"]
).to_frame(index=False)

# EU ETS 적용국: 2005년부터
eu_countries = ["DEU", "ESP", "FRA", "GBR", "IRL", "ITA"]

carbon_panel["CarbonPrice_draft"] = 0.0

carbon_panel.loc[
    carbon_panel["country_code"].isin(eu_countries)
    & (carbon_panel["year"] >= 2005),
    "CarbonPrice_draft"
] = 1.0

# 그 밖의 국가 단위 제도
carbon_panel.loc[
    (carbon_panel["country_code"] == "NZL")
    & (carbon_panel["year"] >= 2008),
    "CarbonPrice_draft"
] = 1.0

carbon_panel.loc[
    (carbon_panel["country_code"] == "MEX")
    & (carbon_panel["year"] >= 2014),
    "CarbonPrice_draft"
] = 1.0

carbon_panel.loc[
    (carbon_panel["country_code"] == "CAN")
    & (carbon_panel["year"] >= 2019),
    "CarbonPrice_draft"
] = 1.0

# 호주 CPM: 2012–2013년 시행, 2014년은 연중 폐지되어 별도 검토
carbon_panel.loc[
    (carbon_panel["country_code"] == "AUS")
    & (carbon_panel["year"].isin([2012, 2013])),
    "CarbonPrice_draft"
] = 1.0

carbon_panel.loc[
    (carbon_panel["country_code"] == "AUS")
    & (carbon_panel["year"] == 2014),
    "CarbonPrice_draft"
] = float("nan")

carbon_panel

    country_code  year  CarbonPrice_draft
0            AUS  2000                0.0
1            AUS  2001                0.0
2            AUS  2002                0.0
3            AUS  2003                0.0
4            AUS  2004                0.0
..           ...   ...                ...
215          USA  2015                0.0
216          USA  2016                0.0
217          USA  2017                0.0
218          USA  2018                0.0
219          USA  2019                0.0

[220 rows x 3 columns]

In [20]:
carbon_panel[
    carbon_panel["year"].isin([2004, 2005, 2008, 2012, 2013, 2014, 2015, 2019])
].pivot(
    index="country_code",
    columns="year",
    values="CarbonPrice_draft"
)

year          2004  2005  2008  2012  2013  2014  2015  2019
country_code
AUS            0.0   0.0   0.0   1.0   1.0   NaN   0.0   0.0
CAN            0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0
DEU            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
ESP            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
FRA            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
GBR            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
IRL            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
ITA            0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0
MEX            0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0
NZL            0.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0
USA            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

In [21]:
carbon_panel.to_csv(
    project / "processed_data" / "carbon_price_panel_draft_2000_2019.csv",
    index=False
)

In [22]:
cpu_panel = pd.read_csv(
    project / "processed_data" / "cpu_long_2000_2019.csv"
)

carbon_panel = pd.read_csv(
    project / "processed_data" / "carbon_price_panel_draft_2000_2019.csv"
)

panel = cpu_panel.merge(
    carbon_panel,
    on=["country_code", "year"],
    how="inner",
    validate="one_to_one"
)

print("행·열 수:", panel.shape)
print("국가 수:", panel["country_code"].nunique())
print("중복 국가·연도:", panel.duplicated(["country_code", "year"]).sum())
print("CPU 결측:", panel["CPU"].isna().sum())
print("탄소가격 변수 결측:", panel["CarbonPrice_draft"].isna().sum())

panel.head()

행·열 수: (220, 4)
국가 수: 11
중복 국가·연도: 0
CPU 결측: 13
탄소가격 변수 결측: 1

  country_code  year        CPU  CarbonPrice_draft
0          AUS  2000  37.986378                0.0
1          AUS  2001  32.302196                0.0
2          AUS  2002  23.147430                0.0
3          AUS  2003  32.739329                0.0
4          AUS  2004  32.399758                0.0

In [23]:
panel.to_csv(
    project / "processed_data" / "cpu_carbon_panel_draft_2000_2019.csv",
    index=False
)